services:
  open-quiz-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - "8080"
    networks:
      - open-quiz
    restart: unless-stopped

networks:
  open-quiz:
    name: open-quiz
    internal: true