[project]
name = "open-quiz-backend"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "cryptography>=49.0.0",
    "fastapi[standard]>=0.139.2",
    "pwdlib>=0.3.0",
    "pyjwt>=2.13.0",
    "pyotp>=2.10.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
